name: Cloud Workflow


on: 
  push:
    branches: ['main', 'master', 'develop'],
  pull_request: 
    branches: ['main', 'master']

jobs:
  app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working_directory: app/infra
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_version: "1.16.2"
      

    - name: Terraform Init & Validate
      run: | 
        terraform init 
        terraform validate 

