name: Scopelancer

on:
  push:
    branches: ['main', 'master', 'develop']
  pull_request:
    branches: ['main', 'master']

jobs:
  app:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: app/web/scopelancer
    steps:
      - name: Checking repository code
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node.Js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'app/web/scopelancer/pnpm-lock.yaml'

      - name: Install dependencies
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
        run: pnpm install --frozen-lockfile
      
      - name: Generate Prisma Client
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
        run: pnpm exec prisma generate --schema=prisma/schema.prisma

      - name: Check Prettier Format
        run: pnpm dlx prettier --check .

      - name: Check Typescript Types
        run: pnpm exec tsc --noEmit